social_networks:
  - 'facebook\.com'
  - 'reddit\.com'
  - 't\.co'
  - 'twitter\.com'
  - 'wordpres\.com'
  - 'disqus\.com'
  - 'linkedin\.com'
  - 'lnkd\.in'
  - 'blogspot'
  - 'stumbleupon\.com'
  - 'tumblr\.com'
  - 'getpocket\.com'
  - 'glassdoor\.com'
  - 'meetup\.com'
  - 'pinterest\.com'
  - 'plus\.url\.google\.com'
  - 'youtube\.com'
  - 'yammer\.com'
  - 'plus\.google\.com'
  - 'touch\.www'
  - 'diigo\.com'
  - 'news\.ycombinator\.com'
  - 'paper\.li'
  - 'digg\.com'
  - 'bigtent\.com'
  - 'blogger\.com'
  - 'googleplus'
  - 'groups\.google\.com'
  - 'hootsuite\.com'
  - 'instagram\.com'
  - 'instapaper\.com'
  - 'netvibes\.com'
  - 'ow\.ly'
  - 'pinboard\.in'
  - 'quora\.com'
  - 'scoop\.it'
  - 'slashdot\.org'
  - 'tinyurl\.com'
  - 'twitter'
  - 'uk\.pinterest\.com'
  - 'wikihow\.com'
search_engines:
  - 'daum\.net'
  - 'eniro\.se'
  - 'naver\.com'
  - 'google\.'
  - 'yahoo\.com'
  - 'msn\.com'
  - 'bing\.'
  - 'aol\.com'
  - 'lycos\.com'
  - 'ask\.com'
  - 'altavista\.com'
  - 'search\.netscape\.com'
  - 'about\.com'
  - 'mamma\.com'
  - 'alltheweb\.com'
  - 'voila\.fr'
  - 'search\.virgilio\.it'
  - 'baidu\.com'
  - 'alice\.com'
  - 'yandex\.com'
  - 'najdi\.org\.mk'
  - 'aol\.com'
  - 'mamma\.com'
  - 'seznam\.cz'
  - 'search\.com'
  - 'wp\.pl'
  - 'online\.onetcenter\.org'
  - 'szukacz\.pl'
  - 'yam\.com'
  - 'pchome\.com'
  - 'kvasir\.no'
  - 'sesam\.no'
  - 'ozu\.es'
  - 'terra\.com'
  - 'mynet\.com'
  - 'ekolay\.net'
  - 'rambler\.ru'

